app: vjepa
nodes: 16
tasks_per_node: 8
data:
  dataset_type: SdfDataset
  datasets:
    - /home/justwantpost/drive/ShapeNetCore.v2/paths_32_train.csv
  datasets_eval:
    - /home/justwantpost/drive/ShapeNetCore.v2/paths_32_eval.csv
  visualise: false
  # decode_one_clip: true
  batch_size: 32
  num_clips: 1
  num_frames: 32
  tubelet_size: 32
  # sampling_rate: 4
  crop_size: 32
  patch_size: 8
  pin_mem: true
  num_workers: 0
  # filter_short_videos: false
  # clip_duration: null
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
logging:
  folder: /home/justwantpost/drive/jepa/logs_n_checkpoints/
  write_tag: jepa_sdf_no_augs
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 4
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
#  - aspect_ratio:
#      - 0.75
#      - 1.5
#    num_blocks: 2
#    spatial_scale:
#      - 0.7
#      - 0.7
#    temporal_scale:
#      - 1.0
#      - 1.0
#    max_temporal_keep: 1.0
#    max_keep: null
meta:
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_tiny # vit_512
  pred_depth: 12 # 12
  pred_embed_dim: 192 # 512
  in_chans: 1
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 300
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 5     # 300
  warmup: 1
  start_lr: 0.00005 #0.0002
  lr: 0.0001  #0.000625
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0
