app: vjepa
data:
  batch_size: 32
  crop_size: 32
  dataset_type: SdfDataset
  datasets:
  - /home/justwantpost/drive/ShapeNetCore.v2/paths_32_train.csv
  datasets_eval:
  - /home/justwantpost/drive/ShapeNetCore.v2/paths_32_eval.csv
  num_clips: 1
  num_frames: 32
  num_workers: 0
  patch_size: 8
  pin_mem: true
  tubelet_size: 32
  visualise: false
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
logging:
  folder: /home/justwantpost/drive/jepa/logs_n_checkpoints/
  write_tag: jepa_sdf_no_augs
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 4
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  use_sdpa: true
model:
  in_chans: 1
  model_name: vit_tiny
  pred_depth: 12
  pred_embed_dim: 192
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
nodes: 16
optimization:
  clip_grad: 10.0
  ema:
  - 0.998
  - 1.0
  epochs: 5
  final_lr: 1.0e-05
  final_weight_decay: 0.4
  ipe: 300
  ipe_scale: 1.25
  lr: 0.0002
  start_lr: 0.0001
  warmup: 1
  weight_decay: 0.04
tasks_per_node: 8
